#!/usr/bin/env python3
"""Re-confirm the #1185 downgrades via real /agent-eval --calibrate dispatch.

#1185 applied 8 effort-band downgrades off the #1184 baseline. Its own
acceptance criteria asks for a per-agent re-run
(`/agent-eval --calibrate --agent <name>` -> aligned) as verification debt.
`concurrency-review` was already re-confirmed via #1211's hardened-fixture
re-test, so this script covers the remaining 7.

Run LOCALLY, not in a cloud session: each target dispatches real
`claude -p /review-agent <target> <fixture> --json` subprocesses (one per
fixture per band, x --samples), so this costs real tokens/time -- there is
no container-reclaim checkpointing here, unlike
`.claude/evals/baseline-1184/run_baseline_1184.py`, because a local run of
7 small targets does not need it.

Usage:
    python3 scripts/recalibrate_1185.py                  # dispatch + submit
    python3 scripts/recalibrate_1185.py --dry-run         # preflight only
    python3 scripts/recalibrate_1185.py --no-submit       # dispatch, print only
    python3 scripts/recalibrate_1185.py --samples 5        # default 3
    python3 scripts/recalibrate_1185.py --agent doc-review # subset

Requires: `claude` CLI on PATH (dispatch) and, unless --no-submit, `gh` CLI
authenticated against bdfinst/agentic-dev-team (posts the verdict table as
an issue comment).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))
import agent_calibrate as ac  # noqa: E402

# The 7 #1185 downgrades still needing per-agent re-confirmation.
# concurrency-review is excluded: already re-confirmed via #1211.
TARGETS = [
    "a11y-review",
    "component-architecture-review",
    "correctness-review",
    "doc-review",
    "performance-review",
    "refactor-opportunity-review",
    "spec-compliance-review",
]

ISSUE_NUMBER = 1185
REPO_SLUG = "bdfinst/agentic-dev-team"


def build_table(results: list) -> str:
    lines = [
        "## #1185 per-agent re-confirmation",
        "",
        "Re-ran `/agent-eval --calibrate --agent <name>` locally for the 7 "
        "downgraded agents still marked as verification debt "
        "(`concurrency-review` already re-confirmed via #1211).",
        "",
        "| target | declared | calibrated | verdict | high | low | medium |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    not_aligned = []
    for r in results:
        rates = {b: r["band_results"].get(b, {}).get("rate") for b in ac.BANDS}
        fmt = lambda v: f"{v:.0%}" if v is not None else "—"
        lines.append(
            f"| `{r['target']}` | {r['declared_band']} | {r['calibrated_band']} "
            f"| {r['verdict']} | {fmt(rates['high'])} | {fmt(rates['low'])} "
            f"| {fmt(rates['medium'])} |"
        )
        if r["verdict"] != "aligned":
            not_aligned.append(r["target"])
    lines.append("")
    if not_aligned:
        lines.append(
            f"⚠️ **Not aligned:** {', '.join(not_aligned)} — the applied "
            "downgrade did not reconfirm against a fresh dispatch. Needs "
            "human review before treating the band as settled."
        )
    else:
        lines.append("✅ All 7 reconfirmed `aligned` — the #1185 downgrades hold.")
    lines.append("")
    lines.append("_Generated by `scripts/recalibrate_1185.py`._")
    return "\n".join(lines)


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--samples", type=int, default=3,
                     help="majority-vote samples per (fixture, band) cell (default 3)")
    ap.add_argument("--agent", action="append", dest="agents",
                     help="limit to this target (repeatable); default: all 7")
    ap.add_argument("--dry-run", action="store_true",
                     help="print the cost preflight and exit without dispatching")
    ap.add_argument("--no-submit", action="store_true",
                     help="dispatch and print the table, but don't post to GitHub")
    ap.add_argument("--issue", type=int, default=ISSUE_NUMBER)
    args = ap.parse_args(argv)

    targets = args.agents or TARGETS
    unknown = set(targets) - set(TARGETS)
    if unknown:
        print(f"error: not in the #1185 downgrade set: {sorted(unknown)}", file=sys.stderr)
        return 2

    dirs = ac.Dirs(REPO_ROOT)
    routing_path = dirs.knowledge / "model-routing.json"
    ladder_path = REPO_ROOT / ".claude" / "model-ladder.json"
    cache_path = REPO_ROOT / "evals" / ".eval-cache.json"
    records_path = REPO_ROOT / ".claude" / "evals" / "calibration-records.json"
    reports_dir = REPO_ROOT / ".claude" / "evals" / "reports"

    floors = ac.load_floors(dirs.knowledge / "calibration-floors.json")
    quarantined = ac.load_quarantine(REPO_ROOT / "memory" / "eval-variance.json")

    all_pairs = []
    for t in targets:
        all_pairs.extend(ac.fixtures_for_target(t, dirs))
    worst_case, hits, net = ac.cost_preflight(all_pairs, dirs, cache_path, routing_path, ladder_path)
    print(f"cost preflight: {net} dispatch(es) worst-case "
          f"({worst_case} fixtures x bands - {hits} cache hit(s)), "
          f"x{args.samples} samples = up to {net * args.samples} real dispatches")

    if args.dry_run:
        print("--dry-run: stopping before dispatch")
        return 0

    flapped: set = set()
    # Route through the infra-aware wrapper: real_dispatch_fn now raises
    # DispatchError on a failed/throttled/session-bleed dispatch instead of
    # banking it as a false negative (#1219). The wrapper retries transient
    # infra failures and re-raises only if unrecoverable.
    dispatch_fn = lambda pair, model: ac.dispatch_with_infra_retry(pair, model, dirs)  # noqa: E731
    pass_rate_fn = ac.make_pass_rate_fn(dispatch_fn, args.samples, flapped)

    results = []
    for t in targets:
        print(f"calibrating {t} ...", flush=True)
        result = ac.calibrate_target(t, dirs, floors, quarantined, pass_rate_fn, routing_path, ladder_path)
        results.append(result)
        print(f"  -> {result['verdict']} (declared={result['declared_band']} "
              f"calibrated={result['calibrated_band']})", flush=True)

    rhash = ac.routing_hash(routing_path, ladder_path if ladder_path.exists() else None)
    records = ac.load_records(records_path)
    for r in results:
        if r["verdict"] != "uncalibratable":
            records[r["target"]] = ac.build_record(r, rhash)
    ac.save_records(records_path, records)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    report = ac.render_report(results, timestamp, (worst_case, hits, net), sorted(flapped))
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"{timestamp}-calibration-1185.md"
    report_path.write_text(report)
    print(f"full report: {report_path}")

    table = build_table(results)
    print("\n" + table)

    if args.no_submit:
        print("\n--no-submit: not posting to GitHub")
        return 0

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(table)
        body_path = f.name
    cmd = ["gh", "issue", "comment", str(args.issue), "--repo", REPO_SLUG,
           "--body-file", body_path]
    print(f"\nposting to {REPO_SLUG}#{args.issue} ...")
    proc = subprocess.run(cmd)
    if proc.returncode != 0:
        print("error: gh issue comment failed -- is `gh auth status` logged in?", file=sys.stderr)
        return proc.returncode
    print("posted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
